accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views

app_name = 'accounts'

urlpatterns = [
	url(r'^signup/$', views.signup, name="signup"),
	url(r'^signup-official/$', views.signup_official, name="signup-official"),
	url(r'^login/$', views.login_view, name="login"),
	url(r'^logout/$', views.logout_view, name="logout"),
	url(r'^dashboard/$', views.dashboard, name="dashboard"),
	url(r'^edit-profile/$', views.edit_profile, name="edit-profile"),
	url(r'^edit-official/$', views.edit_official, name="edit-official"),
	url(r'^password-reset/$', PasswordResetView.as_view(template_name='accounts/password_reset_form.html', email_template_name='accounts/password_reset_email.html', success_url='password-reset-done'), name='password-reset'),
    url(r'^password-reset/password-reset-done/$', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password-reset-done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html', success_url='done'), name='password-reset-confirm'),
    url(r'^password-reset/confirm/MTc/set-password/done/$', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password-reset-complete'),
]

api/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from rest_framework import routers
from api.views import views_portal, views_accounts, views_authentication

router = routers.DefaultRouter()
router.register('slot',views_portal.SlotView, base_name="slotList")
router.register('application', views_portal.ApplicationView, base_name="applicationList")
router.register('fee', views_portal.FeeView, base_name="feeList")
router.register('applicant', views_accounts.ApplicantView, base_name="applicatnList")
router.register('user', views_accounts.UserView, base_name="userList")

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^login/$', views_authentication.LoginView.as_view(), name='api_login'),
    # URLs that require a user to be logged in with a valid session / token.
    url(r'^logout/$', views_authentication.LogoutView.as_view(), name='api_logout'),
]

portal/urls.py
from django.conf.urls import url
from . import views
from portal.views import views_applicant as applicant
from portal.views import views_official as official

app_name = 'portal'

urlpatterns = [
	#applicant urls
	url(r'^index/$', applicant.index, name="index"),
	url(r'^internship/form/$', applicant.internship_form, name="internship-form"),
	url(r'^internship/details/$', applicant.internship_details, name="internship-details"),
	url(r'^internship/edit/$', applicant.edit_internship, name="internship-edit"),
	url(r'^applications/$', applicant.application_home, name="applications"),
	url(r'^application/form/(?P<pk>\d+)/$', applicant.application_form, name="application-form"),
	url(r'^application/filled/(?P<pk>\d+)/$', applicant.application_filled, name="application-filled"),
	url(r'^application/status/$', applicant.application_status, name='application-status'),
	url(r'^pay/fee/(?P<pk>\d+)/$', applicant.pay_fees, name="pay-fee"),
	url(r'^pay/fee/online/(?P<pk>\d+)/$', applicant.pay_fee_online, name="pay-fee-online"),
	url(r'^pay/fee/challan/(?P<pk>\d+)/$', applicant.pay_fee_challan, name="pay-fee-challan"),
	url(r'^pay/fee/(?P<pk>\d+)/paid$', applicant.fees_paid, name="fees-paid"),
	url(r'^final/list/$', applicant.final_list, name="final-list"),
	url(r'^get/documents/(?P<pk>\d+)/$', applicant.get_documents, name="get-documents"),
	#official urls
	url(r'^application/all/$', official.all_applications, name="all-applications"),
	url(r'^application/(?P<pk>\d+)/$', official.application_details, name="application-details"),
	url(r'^application/verify/(?P<pk>\d+)/$', official.application_verify, name="application-verify"),
	url(r'^application/reject/(?P<pk>\d+)/$', official.application_reject, name="application-reject"),
	url(r'^slot/new/$', official.create_slot, name="create-slot"),
	url(r'^slot/(?P<pk>\d+)/edit/$', official.edit_slot, name="edit-slot"),
	url(r'^slot/all/$', official.all_slots, name="all-slots"),
	url(r'^slot/(?P<pk>\d+)/delete/$', official.DeleteSlot.as_view(), name='delete-slot'),
	url(r'^fess/payments/all/$', official.all_fees, name="all-fees"),
	url(r'^fee/(?P<pk>\d+)/details$', official.fee_details, name="fee-details"),
	url(r'^fee/verify/(?P<pk>\d+)/$', official.fee_verify, name="fee-verify"),
	url(r'^fee/reject/(?P<pk>\d+)/$', official.fee_reject, name="fee-reject"),
	#docs
	url(r'^acknowledgement/(?P<pk>\d+)/$', applicant.acknowledgement_slip, name="acknowledgement"),
	url(r'^acceptance/(?P<pk>\d+)/$', applicant.acceptance_letter, name="acceptance"),
	url(r'^temp-pass/(?P<pk>\d+)/$', applicant.temp_pass, name="temp-pass"),
	url(r'^attendance/(?P<pk>\d+)/$', applicant.attendance_letter, name="attendance"),
	url(r'^clearance/(?P<pk>\d+)/$', applicant.clearance_letter, name="clearance"),
	url(r'^bond/(?P<pk>\d+)/$', applicant.bond_format, name="bond"),
	url(r'^rules/$', applicant.rules, name="rules"),
]

portalsite/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from accounts.views import home_page
from portal.views import views_applicant


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name='home_page'),
    url(r'^about/$', views_applicant.about, name='about'),
    url(r'^contact/$', views_applicant.contact, name='contact'),
    url(r'^help/$', views_applicant.help_content, name='help'),
    url(r'^portal/', include('portal.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^feedback/',include('feedback.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

portal/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.utils import timezone
import datetime

# Create your models here.
class Slot(models.Model):
	start_date = models.DateField(default=timezone.now, null=True)
	end_date = models.DateField(default=timezone.now, null=True)
	duration = models.IntegerField(default=7,null=True)
	max_strength = models.IntegerField(default=10,null=True)
	present_strength = models.IntegerField(default=0,null=True)
	is_filled = models.BooleanField(default=False)

	def get_absolute_url(self):
		return reverse('portal:all-slots')

	def __str__(self):
		return str(self.start_date) + " - " + str(self.end_date) + " :: " + str(self.present_strength) + " filled"

class Application(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	application_no = models.CharField(max_length=8, default='00XX0000')
	applicant_name = models.CharField(max_length=250, default='')
	GENDER_CHOICES = (
		('M','Male'),
		('F','Female'),
	)
	gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='M')
	caste = models.CharField(max_length=100, default='')
	residence_address = models.TextField(default='')
	college_name = models.CharField(max_length=500, default='')
	college_address = models.TextField(default='')
	mobile_no = models.CharField(max_length=10,default='')
	date_of_birth = models.DateField(default=timezone.now)
	email = models.EmailField(null=True)
	applicant_photo = models.FileField(null=True, help_text="upload jpg, jpeg, png files only", validators=[FileExtensionValidator(['jpg','png','jpeg'])])
	noc = models.FileField(null=True,help_text="upload pdf,jpg,jpeg,png files only with size less than 2mb")
	caste_certificate = models.FileField(null=True,help_text="upload pdf,jpg,jpeg,png files only with size less than 2mb")
	internship_type = models.CharField(max_length=50, default="Training")
	duration = models.IntegerField(default=7)
	slot = models.ForeignKey(Slot, on_delete=models.CASCADE, null=True)
	course = models.CharField(max_length=250,default='')
	year_of_study = models.CharField(max_length=10, default='Third')
	department = models.CharField(max_length=250, default='')
	is_application_filled = models.BooleanField(default=False)
	verified = models.BooleanField(default=False)
	remarks = models.TextField(null=True)

	def get_absolute_url(self):
		return reverse('portal:application-filled')

	def __str__(self):
		return self.application_no

class Fee(models.Model):
	application = models.OneToOneField(Application, on_delete=models.CASCADE)
	fee_receipt = models.FileField(null=True,help_text="upload pdf,jpg,jpeg,png files only with size less than 2mb")
	FEE_CHOICES = (
		('O', 'Online'),
		('C', 'Challan'),
	)
	fee_type = models.CharField(max_length=1, choices=FEE_CHOICES, default='O')
	transaction_no = models.CharField(max_length=20,default='')
	fees = models.FloatField(default=200.0)
	paid_on = models.DateTimeField(default=timezone.now,help_text="enter only date in yyyy/mm/dd format")
	is_fees_paid = models.BooleanField(default=False)
	verified = models.BooleanField(default=False)
	remarks = models.TextField(null=True)

	def get_absolute_url(self):
		return reverse('portal:applications')

	def __str__(self):
		return str(self.transaction_no)

portal/views/views_official.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q
import datetime
import re
from portal.models import Application, Fee, Slot
from accounts.models import Applicant, Official
from portal.forms import ApplicationRemarksForm, SlotForm, FeeRemarksForm

#official views

@login_required
def create_slot(request):
	try:
		if request.user.official:
			if request.method == 'POST':
				form = SlotForm(request.POST)
				if form.is_valid():
					form.save()
					return redirect('portal:all-slots')
			else:
				form = SlotForm()
			return render(request, 'official/create_slot.html', {'form':form})
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

@login_required
def edit_slot(request,pk):
	try:
		if request.user.official:
			slot = get_object_or_404(Slot, pk=pk)
			if request.method == 'POST':
				form = SlotForm(request.POST, instance=slot)
				if form.is_valid():
					form.save()
					return redirect('portal:all-slots')
			else:
				form = SlotForm(instance=slot)
			return render(request, 'official/create_slot.html', {'form':form})
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

@login_required
def all_slots(request):
	try:
		if request.user.official:
			slots = Slot.objects.all().order_by('start_date')
			return render(request, 'official/all_slots.html', {'slots':slots})
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

@method_decorator(login_required, name='dispatch')
class DeleteSlot(DeleteView):
    model = Slot
    template_name = 'official/slot_confirm_delete.html'
    success_url = reverse_lazy('portal:all-slots')

@login_required
def all_applications(request):
	try:
		if request.user.official:
			query = request.GET.get("q")
			if query:
				match_app_no = re.match(r'\d{2}[a-zA-Z]{2}\d{4}', query)
				if match_app_no:
					try:
						application = Application.objects.get(application_no=query)
						return render(request, 'official/all_applications.html', {'search_app':application})
					except Application.DoesNotExist:
						messages.error(request, "No application found with {}".format(query))
				else:
					messages.error(request, "Invalid application number")
			applications = Application.objects.all().order_by('pk')
			return render(request, 'official/all_applications.html', {'applications':applications})
	except Official.DoesNotExist:
		messages.error(request,"Not authorized")
		return redirect('portal:index')

@login_required
def application_details(request,pk):
	try:
		if request.user.official:
			application = get_object_or_404(Application, pk=pk)
			return render(request, 'official/application_details.html', {'application':application})
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

@login_required
def application_verify(request,pk):
	try:
		if request.user.official:
			application = get_object_or_404(Application, pk=pk)
			if application.is_application_filled == True:
				application.verified = True
				application.remarks = "Application accepted"
				application.save()
				applications = Application.objects.filter(user=application.user)
				fee = Fee.objects.create(application=application)
				fee.fees = 200.00
				fee.save()
				messages.success(request,"Application verified")
				return redirect('portal:application-details',pk=pk)
			else:
				messages.error(request,"Application not filled yet")
				return redirect('portal:index')
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

@login_required
def application_reject(request,pk):
	try:
		if request.user.official:
			application = get_object_or_404(Application , pk=pk)
			if request.method == 'POST':
				form = ApplicationRemarksForm(request.POST)
				if form.is_valid():
					application.remarks = form.cleaned_data['remarks']
					application.is_application_filled = False
					application.save()
					messages.info(request, "Application rejected")
					return redirect('portal:application-details',pk=pk)
			else:
				form = ApplicationRemarksForm()
			return render(request, 'official/remarks.html', {'form':form})
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

@login_required
def all_fees(request):
	try:
		if request.user.official:
			query = request.GET.get("q")
			if query:
				try:
					transaction = Fee.objects.get(transaction_no=query)
					return render(request, 'official/all_fees.html', {'transaction':transaction})
				except Fee.DoesNotExist:
					messages.error(request, "No transaction found with {}".format(query))
			fees = Fee.objects.filter(is_fees_paid=True).order_by('pk')
			return render(request, 'official/all_fees.html', {'fees':fees})
	except Official.DoesNotExist:
		messages.error(request,"Not authorized")
		return redirect('portal:index')

@login_required
def fee_details(request,pk):
	try:
		if request.user.official:
			fee = get_object_or_404(Fee, pk=pk)
			return render(request, 'official/fee_details.html', {'fee':fee})
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

@login_required
def fee_verify(request,pk):
	try:
		if request.user.official:
			fee = get_object_or_404(Fee, pk=pk)
			if fee.is_fees_paid == True:
				fee.verified = True
				fee.remarks = "Application accepted"
				fee.save()
				applications = Application.objects.filter(user=fee.application.user)
				applicant_of_app = fee.application.user.applicant
				fees_no = 0
				for app in applications:
					try:
						if app.fee:
							if app.fee.verified:
								fees_no += 1
					except:
						pass
				if fees_no == applications.count():
					applicant_of_app.reporting_date = str(applicant_of_app.slot.start_date) + " " + str(datetime.time(hour=10, minute=0))
					applicant_of_app.is_group_formed = True
				applicant_of_app.save()
				messages.success(request,"Fee payment details verified")
				return redirect('portal:fee-details',pk=pk)
			else:
				messages.error(request,"Fee not paid yet")
				return redirect('portal:index')
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

@login_required
def fee_reject(request,pk):
	try:
		if request.user.official:
			fee = get_object_or_404(Fee , pk=pk)
			if request.method == 'POST':
				form = FeeRemarksForm(request.POST)
				if form.is_valid():
					fee.remarks = form.cleaned_data['remarks']
					fee.is_fees_paid = False
					fee.save()
					messages.info(request, "Fee payment rejected")
					return redirect('portal:fee-details',pk=pk)
			else:
				form = FeeRemarksForm()
			return render(request, 'official/remarks.html', {'form':form})
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

portal/templates/applicant/acknowledgement.html
<html>
<head>
	<title>Acknowledgement</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'portal/base.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'portal/pdf.css' %}">
</head>
<body>
	<div class="pdf-header">
		<div class="form-header">
			<table class="pdf-table">
				<tbody>
					<tr>
						<td style="border: 0;" width="100">
							<img src="{% static 'portal/logo.png' %}" height="100" />
						</td>
						<td style="border: 0;" width="400">
							<h4 align="center"><strong>Hindustan Shipyard Limited</strong></h4>
							<h4 align="center">Visakhapatnam-530 005</h4>
							<h3 align="center"><strong>Acknowledgement Slip</strong></h3>
						</td>
					</tr>
				</tbody>
			</table>
		</div>

		<div class="pdf-photo">
			<img src="{{ application.applicant_photo.url }}" alt="{{ application.applicant_name }}" width="110px" />
		</div>
	</div>
		
		
	<table class="table table-bordered">
		<thead>
			<tr>
				<th colspan="4" style="text-align: center;">
					<h3>{{ application.application_no }}</h3>
				</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th>Name</th>
				<td>
					{{ application.applicant_name }}
				</td>
				<th>Date of birth</th>
				<td>{{ application.date_of_birth }}</td>
			</tr>
			<tr>
				<th>Mobile no</th>
				<td>{{ application.mobile_no }}</td>
				<th>E-mail</th>
				<td>{{ application.email }}</td>		
			</tr>
			<tr>
				<th>Gender</th>
				<td>{{ application.get_gender_display }}</td>
				<th>Caste</th>
				<td>{{ application.caste }}</td>
			</tr>
			<tr>
				<th>Course</th>
				<td>{{ application.course }}</td>
				<th>Department</th>
				<td>{{ application.user.applicant.get_department_display }}</td>
			</tr>
			<tr>
				<th>College name</th>
				<td colspan="3">{{ application.college_name }}</td>
			</tr>
			<tr>
				<th>College Address</th>
				<td colspan="3">{{ application.college_address }}</td>
			</tr>
			<tr>
				<th>Residential Adddress</th>
				<td colspan="3">{{ application.residence_address }}</td>
			</tr>
			<tr>
				<th>Internship type</th>
				<td>{{ application.user.applicant.get_internship_type_display }}</td>
				<th>Slot</th>
				<td>{{ application.slot.start_date }} - {{ application.slot.end_date }}</td>
			</tr>
			{% if fee.verified %}
				<tr>
					<th colspan="4"><h4 align="center">Fee details</h4></th>
				</tr>
				<tr>
					<th>Transaction no</th>
					<td>{{fee.transaction_no}}</td>
					<th>Fee amount paid</th>
					<td>{{fee.fees}}</td>
				</tr>
				<tr>
					<th colspan="4"><h4 align="center">{{application.user.applicant.get_internship_type_display}} details</h4></th>
				</tr>
				<tr>
					<th>Reporting date</th>
					<td>{{ application.user.applicant.reporting_date|date }}</td>
					<th>Reporting time</th>
					<td>{{ application.user.applicant.reporting_date|time }}</td>
				</tr>
			{% endif %}
		</tbody>
	</table>
	<div class="container-fluid" style="text-align: center;">
		<button class="btn btn-success btn-xs" onclick="window.print()">
			Print			
		</button>
	</div>
</body>

portal/templates/applicant/applicant_index.html
{% extends 'applicant/base.html' %}

{% block title %}Student Portal{% endblock %}

{% block content %}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-offset-3 col-md-offset-3 col-sm-6 col-md-6 col-12">
			{% if user.applicant %}

				<div class="panel panel-default">
					<div class="panel-body">
						{% include 'applicant/messages.html' %}

						{% if profile.is_filled %}
							{% if profile.is_group_formed %}
								<div class="container-fluid text-center">
									Download and print the documents below before reporting to the venue<br>
									<a href="{% url 'portal:final-list' %}"><button type="button" class="btn btn-success">Get documents</button></a>
								</div>
							{% else %}
								<div class="text-center">
									<a href="{% url 'portal:applications' %}"><button type="button" class="btn btn-success">Fill Applications</button></a>
								</div>
							{% endif %}
							
							<table class="table">
								<thead>
									<tr>
										<th colspan="2" class="text-center">Group details</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<th>Internship type</th>
										<td>
											{% if profile.internship_type == 'T' %}
												Training
											{% else %}
												Project
											{% endif %}
										</td>
									</tr>
									<tr>
										<th>Duration</th>
										<td>{{ profile.duration }}</td>
									</tr>
									<tr>
										<th>Slot</th>
										<td>{{ profile.slot }}</td>
									</tr>
									<tr>
										<th>Course</th>
										<td>{{ profile.course }}</td>
									</tr>
									<tr>
										<th>Department</th>
										<td>{{ profile.department }}</td>
									</tr>
									<tr>
										<th>Group strength</th>
										<td>{{ profile.group_strength }}</td>
									</tr>
								</tbody>
							</table>
							{% if profile.is_group_formed %}
							{% else %}
								<div class="text-center">
									<strong class="text-danger">Deleting form will delete all the applications submitted and new applications will be rendered</strong>
									<a href="{% url 'portal:internship-edit' %}"><button type="button" class="btn btn-danger">Delete and fill new form</button></a>
								</div>
							{% endif %}
						{% else %}
							<div class="container-fluid text-center">
								Start filling internship details to continue
								<a href="{% url 'portal:internship-form' %}"><button type="button" class="btn btn-info">Fill Application</button></a>
							</div>
						{% endif %}
					</div>
				</div>
			{% else %}

				<div class="panel panel-default">
					<div class="panel-body">
						{% include 'applicant/messages.html' %}
					</div>
				</div>

			{% endif %}
		</div>
	</div>
</div>

{% endblock %}

portal/templates/applicant/application_home.html
{% extends 'applicant/base.html' %}

{% block title %}Application{% endblock %}

{% block content %}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-offset-3 col-md-offset-3 col-sm-6 col-md-6 col-12">
			<div class="panel panel-default">
				<div class="panel-body">
					{% include 'applicant/messages.html' %}
					<h3 class="text-center">Applications</h3>
					<table class="table">
						<thead>
							<tr>
								<th>Application</th>
								<th>Actions</th>
								<th>Remarks</th>
								<th class="text-center">Fees</th>
							</tr>
						</thead>
						<tbody>
						{% for application in applications %}
							<tr>
								<td>
									{% if application.is_application_filled %}
										<a href="#">{{ application.applicant_name }}</a> - {{ application.application_no }} &nbsp;
										{% if application.verified %}
											<span class="text-success">Verified</span>
										{% else %}
											<span class="text-danger">Not verified</span>
										{% endif %}
									{% else %}
										Application - {{ forloop.counter }}
									{% endif %}
								</td>
								{% if application.is_application_filled %}
									<td>
										<a href="javascript: printonclick()"><button type="button" class="btn btn-success btn-sm">Acknowledgement &nbsp;<span class="glyphicon glyphicon-download"></span></button></a>
										<script type="text/javascript">
											function printonclick(){
												acknowledgement = window.open("{% url 'portal:acknowledgement' application.id %}", 'Acknowledgement');
												acknowledgement.print();
												acknowledgement.onafterprint = function() {
													acknowledgement.close();
												}
											}
										</script>
									</td>
								{% else %}
									<td>
										<a href="{% url 'portal:application-form' application.pk %}"><button type="button" class="btn btn-info btn-sm">Edit &nbsp;<span class="glyphicon glyphicon-plus-sign"></span></button></a>
									</td>
								{% endif %}
								{% if application.remarks %}
									<td>
										<span class="text-{% if application.verified %}success{% else %}danger{% endif %}">{{ application.remarks }}</span>
									</td>
								{% endif %}
								{% if application.is_application_filled %}
									{% if application.verified %}
										{% if application.fee.is_fees_paid %}
											{% if application.fee.verified %}
												<td>
													<span class="text-success">Verified</span>
												</td>
											{% else %}
												<td>
													<span class="text-success">Paid. Not verified</span>
												</td>
											{% endif %}
										{% else %}
											<td>
												Rs. {{ application.fee.fees }}
												<a href="{% url 'portal:pay-fee' application.fee.pk %}"><button type="button" class="btn btn-success btn-sm">Pay</button></a>
											</td>
										{% endif %}
									{% endif %}
								{% endif %}
							</tr>
						{% endfor %}
						</tbody>
					</table>
					{% if fee %}
						<div class="container-fluid" style="margin-top: 30px;">
							<div>
								<strong>Reporting date : </strong><span>{{ applicant.reporting_date|date:"D d M Y" }} @ {{ applicant.reporting_date|time:"H:i" }} A.M</span><br>
								{% if not fee.is_fees_paid %}
									<strong>Fee amount : </strong><span>{{ fee.fees }}</span><br>
									<a href=""><button type="button" class="btn btn-success">Pay fees</button></a>
								{% else %}
									<strong>Fees paid <a href="">View receipt</a></strong>
								{% endif %}
							</div>
						</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

portal/templates/applicant/application_status.html
{% extends 'applicant/base.html' %}

{% block title %}Application Status{% endblock %}

{% block content %}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-offset-3 col-md-offset-3 col-sm-6 col-md-6 col-12">
			<div class="panel panel-default">
				<div class="panel-body">
					{% include 'applicant/messages.html' %}
					<h3 class="text-center">Application Status</h3>
					{% if application %}
						<div class="container-fluid text-center">
							{% if application.verified %}
								<span>{{ application.application_no }}</span>
								<br/>
								<span class="text-success">Application verified</span>
								<br/>
								{% if application.fee.is_fees_paid %}
									{% if application.fee.verified %}
										<span class="text-success">Fee details verified</span>
									{% else %}
										<span class="text-danger">Fee paid. Details not verified yet</span>
									{% endif %}
								{% endif %}
								<br/>
								<span>Please <a href="{% url 'accounts:login' %}">login</a> to proceed to next steps</span>
							{% else %}
								<span>{{ application.application_no }}</span>
								<br/>
								{% if application.is_application_filled %}
									<span class="text-danger">Application not verified</span>
									<br/>
									<span>Contact the officials</span>
								{% else %}
									<span class="text-danger">Application rejected</span>
									<br/>
									<span>Please <a href="{% url 'accounts:login' %}">login</a> and check the errors or contact the offficials</span>
								{% endif %}	
							{% endif %}
						</div>
					{% else %}
						<div class="container-fluid">
							<h4 class="text-center">Enter application number</h4>
						</div>
						<form class="text-center" role="search" method="get" action="">
	                        <div class="form-group">
	                            <input type="text" class="form-control" name="q" value="{{ request.GET.q }}" />
	                        </div>
	                        <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
	                    </form>
	                {% endif %}
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}