accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views

app_name = 'accounts'

urlpatterns = [
	url(r'^signup/$', views.signup, name="signup"),
	url(r'^signup-official/$', views.signup_official, name="signup-official"),
	url(r'^login/$', views.login_view, name="login"),
	url(r'^logout/$', views.logout_view, name="logout"),
	url(r'^dashboard/$', views.dashboard, name="dashboard"),
	url(r'^edit-profile/$', views.edit_profile, name="edit-profile"),
	url(r'^edit-official/$', views.edit_official, name="edit-official"),
	url(r'^password-reset/$', PasswordResetView.as_view(template_name='accounts/password_reset_form.html', email_template_name='accounts/password_reset_email.html', success_url='password-reset-done'), name='password-reset'),
    url(r'^password-reset/password-reset-done/$', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password-reset-done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html', success_url='done'), name='password-reset-confirm'),
    url(r'^password-reset/confirm/MTc/set-password/done/$', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password-reset-complete'),
]

api/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from rest_framework import routers
from api.views import views_portal, views_accounts, views_authentication

router = routers.DefaultRouter()
router.register('slot',views_portal.SlotView, base_name="slotList")
router.register('application', views_portal.ApplicationView, base_name="applicationList")
router.register('fee', views_portal.FeeView, base_name="feeList")
router.register('applicant', views_accounts.ApplicantView, base_name="applicatnList")
router.register('user', views_accounts.UserView, base_name="userList")

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^login/$', views_authentication.LoginView.as_view(), name='api_login'),
    # URLs that require a user to be logged in with a valid session / token.
    url(r'^logout/$', views_authentication.LogoutView.as_view(), name='api_logout'),
]

portal/urls.py
from django.conf.urls import url
from . import views
from portal.views import views_applicant as applicant
from portal.views import views_official as official

app_name = 'portal'

urlpatterns = [
	#applicant urls
	url(r'^index/$', applicant.index, name="index"),
	url(r'^internship/form/$', applicant.internship_form, name="internship-form"),
	url(r'^internship/details/$', applicant.internship_details, name="internship-details"),
	url(r'^internship/edit/$', applicant.edit_internship, name="internship-edit"),
	url(r'^applications/$', applicant.application_home, name="applications"),
	url(r'^application/form/(?P<pk>\d+)/$', applicant.application_form, name="application-form"),
	url(r'^application/filled/(?P<pk>\d+)/$', applicant.application_filled, name="application-filled"),
	url(r'^application/status/$', applicant.application_status, name='application-status'),
	url(r'^pay/fee/(?P<pk>\d+)/$', applicant.pay_fees, name="pay-fee"),
	url(r'^pay/fee/online/(?P<pk>\d+)/$', applicant.pay_fee_online, name="pay-fee-online"),
	url(r'^pay/fee/challan/(?P<pk>\d+)/$', applicant.pay_fee_challan, name="pay-fee-challan"),
	url(r'^pay/fee/(?P<pk>\d+)/paid$', applicant.fees_paid, name="fees-paid"),
	url(r'^final/list/$', applicant.final_list, name="final-list"),
	url(r'^get/documents/(?P<pk>\d+)/$', applicant.get_documents, name="get-documents"),
	#official urls
	url(r'^application/all/$', official.all_applications, name="all-applications"),
	url(r'^application/(?P<pk>\d+)/$', official.application_details, name="application-details"),
	url(r'^application/verify/(?P<pk>\d+)/$', official.application_verify, name="application-verify"),
	url(r'^application/reject/(?P<pk>\d+)/$', official.application_reject, name="application-reject"),
	url(r'^slot/new/$', official.create_slot, name="create-slot"),
	url(r'^slot/(?P<pk>\d+)/edit/$', official.edit_slot, name="edit-slot"),
	url(r'^slot/all/$', official.all_slots, name="all-slots"),
	url(r'^slot/(?P<pk>\d+)/delete/$', official.DeleteSlot.as_view(), name='delete-slot'),
	url(r'^fess/payments/all/$', official.all_fees, name="all-fees"),
	url(r'^fee/(?P<pk>\d+)/details$', official.fee_details, name="fee-details"),
	url(r'^fee/verify/(?P<pk>\d+)/$', official.fee_verify, name="fee-verify"),
	url(r'^fee/reject/(?P<pk>\d+)/$', official.fee_reject, name="fee-reject"),
	#docs
	url(r'^acknowledgement/(?P<pk>\d+)/$', applicant.acknowledgement_slip, name="acknowledgement"),
	url(r'^acceptance/(?P<pk>\d+)/$', applicant.acceptance_letter, name="acceptance"),
	url(r'^temp-pass/(?P<pk>\d+)/$', applicant.temp_pass, name="temp-pass"),
	url(r'^attendance/(?P<pk>\d+)/$', applicant.attendance_letter, name="attendance"),
	url(r'^clearance/(?P<pk>\d+)/$', applicant.clearance_letter, name="clearance"),
	url(r'^bond/(?P<pk>\d+)/$', applicant.bond_format, name="bond"),
	url(r'^rules/$', applicant.rules, name="rules"),
]

portalsite/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from accounts.views import home_page
from portal.views import views_applicant


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name='home_page'),
    url(r'^about/$', views_applicant.about, name='about'),
    url(r'^contact/$', views_applicant.contact, name='contact'),
    url(r'^help/$', views_applicant.help_content, name='help'),
    url(r'^portal/', include('portal.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^feedback/',include('feedback.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import FileExtensionValidator
from django.utils import timezone
from api.models import TokenModel
from portal.models import Slot

# Create your models here.

class Applicant(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	mobile_no = models.CharField(max_length=10,default='')
	TRAINING_CHOICES = (
		('T','Training'),
		('P','Project'),
	)
	DEPARTMENT_CHOICES = (
		('CS','Computer Science Engineering'),
		('CV','Civil Engineering'),
		('CH','Chemical Engineering'),
		('EC','Electronics Engineering'),
		('EE','Electrical Engineering'),
		('ME','Mechanical Engineering'),
		('MT','Metallurgical Engineering'),
		('MN','Mining Engineering'),
	)
	internship_type = models.CharField(max_length=1, choices=TRAINING_CHOICES, default='T')
	duration = models.IntegerField(default=7)
	slot = models.ForeignKey(Slot, on_delete=models.CASCADE, null=True)
	course = models.CharField(max_length=250, default='')
	department = models.CharField(max_length=2, choices=DEPARTMENT_CHOICES, default='CS')
	group_strength = models.IntegerField(default=1)
	reporting_date = models.DateTimeField(default=timezone.now)
	is_filled = models.BooleanField(default=False)
	is_group_formed = models.BooleanField(default=False)

	def get_absolute_url(self):
		return reverse('accounts:dashboard', kwargs={'pk': self.pk})

	@receiver(post_save, sender=settings.AUTH_USER_MODEL)
	def create_auth_token(sender, instance=None, created=False, **kwargs):
	    if created:
	        TokenModel.objects.create(user=instance)

	def __str__(self):
		return self.user.username

class Official(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	mobile_no = models.CharField(max_length=10,default='')
	employee_id = models.CharField(max_length=10, default='')
	designation = models.CharField(max_length=100, default='')

	def get_absolute_url(self):
		return reverse('accounts:dashboard', kwargs={'pk': self.pk})

	def __str__(self):
		return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Applicant, Official

class UserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name','email', 'password1', 'password2',]

	def clean_email(self):
		if User.objects.filter(email__iexact=self.cleaned_data['email']):
			raise forms.ValidationError("Email id already exists")
		return self.cleaned_data['email']

class ApplicantForm(forms.ModelForm):
	class Meta:
		model = Applicant
		fields = ['mobile_no',]

class OfficialForm(forms.ModelForm):
	class Meta:
		model = Official
		fields = ['mobile_no','employee_id','designation',]

class UserEditForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email',]
		exclude = ['username','password1','password2',]

accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django import forms
from .models import Applicant, Official
from .forms import UserForm, ApplicantForm, OfficialForm, UserEditForm

# Create your views here.

def home_page(request):
	if request.user.is_authenticated:
		return redirect('portal:index')
	return render(request, 'accounts/home_page.html')

def login_view(request):
	if request.method == 'POST':
	    username = request.POST['username']
	    password = request.POST['password']
	    user = authenticate(request, username=username, password=password)
	    if user is not None:
	        login(request, user)
	        return redirect('portal:index')
	    else:
	    	messages.error(request, "Invalid username or password")
	form = AuthenticationForm()
	return render(request,'accounts/login.html', {'form' : form})

@login_required
def logout_view(request):
	logout(request)
	return render(request, 'accounts/logged_out.html',{})

def signup(request):
	if request.method == 'POST':
		user_form = UserForm(request.POST,request.FILES)
		profile_form = ApplicantForm(request.POST,request.FILES)
		if user_form.is_valid() and profile_form.is_valid():
			new_user = user_form.save(commit=False)
			new_user.set_password(user_form.cleaned_data['password2'])
			new_user.save()
			profile=Applicant.objects.create(user=new_user)
			profile.mobile_no = profile_form.cleaned_data['mobile_no']
			profile.save()
			return redirect('accounts:login')
	else:
		user_form = UserForm()
		profile_form = ApplicantForm()
	return render(request, 'accounts/register.html', {'user_form':user_form, 'profile_form':profile_form})

def signup_official(request):
	if request.method == 'POST':
		user_form = UserForm(request.POST, request.FILES)
		profile_form = OfficialForm(request.POST, request.FILES)
		if user_form.is_valid() and profile_form.is_valid():
			new_user = user_form.save(commit=False)
			new_user.set_password(user_form.cleaned_data['password2'])
			new_user.save()
			profile = Official.objects.create(user=new_user)
			profile.mobile_no = profile_form.cleaned_data['mobile_no']
			profile.employee_id = profile_form.cleaned_data['employee_id']
			profile.designation = profile_form.cleaned_data['designation']
			profile.save()
			return redirect('accounts:login')
	else:
		user_form = UserForm()
		profile_form = OfficialForm()
	return render(request, 'accounts/official_register.html', {'user_form':user_form, 'profile_form':profile_form})

@login_required
def edit_official(request):
	profile = get_object_or_404(Official, pk=request.user.official.id)
	if request.method == 'POST':
		user_form = UserEditForm(request.POST, request.FILES, instance=request.user)
		profile_form = OfficialForm(request.POST, request.FILES, instance=profile)
		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			return redirect('accounts:dashboard')
	else:
		user_form = UserEditForm(instance=request.user)
		profile_form = OfficialForm(instance=profile)
	return render(request, 'accounts/edit_profile.html', {'user_form':user_form, 'profile_form':profile_form})

@login_required
def edit_profile(request):
	profile = get_object_or_404(Applicant, pk=request.user.applicant.id)
	if request.method == 'POST':
		user_form = UserEditForm(request.POST, request.FILES, instance=request.user)
		profile_form = ApplicantForm(request.POST, request.FILES, instance=profile)
		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			return redirect('accounts:dashboard')
	else:
		user_form = UserEditForm(instance=request.user)
		profile_form = ApplicantForm(instance=profile)
	return render(request, 'accounts/edit_profile.html', {'user_form':user_form, 'profile_form':profile_form})

@login_required
def dashboard(request):
	try:
		if request.user.applicant:
			profile = get_object_or_404(Applicant,pk=request.user.applicant.id)
	except:
		pass
	try:
		if request.user.official:
			profile = get_object_or_404(Official,pk=request.user.official.id)
	except:
		pass
	return render(request,'accounts/dashboard.html',{'profile':profile})

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/base.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/forms.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/widgets.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/responsive.css' %}">
        <script type="text/javascript" src="{% static 'accounts/core.js' %}"></script>
        <script type="text/javascript" src="{% static 'accounts/jquery.init.js' %}"></script>
    </head>

    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'portal:index' %}">Student Online Portal</a>
                </div>

                <div class="collapse navbar-collapse" id="navBar">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'about' %}">About HSL</a></li>
                        <li><a href="{% url 'help' %}">Help</a></li>
                        <li><a href="{% url 'contact' %}">Contact</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li>
                                <a href="{% url 'accounts:dashboard' %}">Dashboard</a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:logout' %}">Logout</a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{% url 'home_page' %}">Login/Register</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </body>
</html>

accounts/templates/accounts/dashboard.html
{% extends 'accounts/base.html' %}

{% block title %} {{ profile.user.first_name }} {{ profile.user.last_name }} {% endblock %}

{% block content %}
	<div class="container-fluid">
		<div class="panel panel-default">
			<div class="panel-body">
				{% if user.applicant %}
					<div class="row" style="text-align: center;">		
						<div class="col-sm-4 col-md-4 col-sm-offset-4 col-md-offset-4">
								<div class="container-fluid">
									<a href="{% url 'accounts:edit-profile' %}"><button type="submit" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-edit"></span>&nbsp; Edit Profile</button></a>
								</div>


							<div class="col-sm-8 col-md-8 col-sm-offset-2 col-md-offset-2">
								<table class="table">
									<thead>
										<tr>
											<th style="text-align: center;">
												{{ profile.user.first_name }} {{ profile.user.last_name }}
											</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>
												Username : {{ profile.user.username }}
											</td>
										</tr>
										<tr>
											<td>
												E-mail : {{ profile.user.email }}
											</td>
										</tr>
										<tr>
											<td>
												Mobile no : {{ profile.mobile_no }}
											</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				{% elif user.official %}
					<div class="row">
						<div class="col-sm-8 col-md-8 col-sm-offset-2 col-md-offset-2">
							<table class="table">
								<thead>
									<tr>
										<th>{{ profile.user.first_name }} {{ profile.user.last_name }}</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>
											Employee id : {{ profile.employee_id }}
										</td>
									</tr>
									<tr>
										<td>
											Designation : {{ profile.designation }}
										</td>
									</tr>
									<tr>
										<td>
											Mobile no : {{ profile.mobile_no }}
										</td>
									</tr>
								</tbody>
							</table>	
						</div>
					</div>
					<div class="row">
						<div class="container-fluid" style="text-align: center;">
							<a href="{% url 'accounts:edit-official' %}"><button type="submit" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-edit"></span>&nbsp; Edit Profile</button></a>
						</div>
					</div>
				{% else %}
					<div class="row">
						<div class="container-fluid">
							<p class="text-danger">No Dashboard</p>
						</div>		
					</div>		
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

accounts/templates/accounts/form_template.html
<fieldset class="module aligned">
	{% for field in form %}
		<div class="form-row">
			<div class="text-center">
				{{field.error}}
			</div>
			<div>
				<label class="required">
					{{ field.label_tag }} 
				</label>
				{{ field }}
			</div>
			{% if field.help_text %}
				<div class="help" style="color: gray;">{{ field.help_text }}</div>
			{% endif %}
		</div>
	{% endfor %}
</fieldset>

accounts/templates/accounts/home_page.html
{% extends 'accounts/profile_base.html' %}

{% block title %}Student Portal{% endblock %}

{% block content %}

<div class="container-fluid">
	<div class="row">
		{% include 'accounts/messages.html' %}
		<h3 style="text-align: center;">Login</h3>
		<a href="{% url 'accounts:login' %}">
			<div class="col-sm-4 col-md-4 col-12 col-sm-offset-4 col-md-offset-4">
				<div class="panel homePage" style="background-color: #FFC300;">
					<div class="panel-body">
						<span class="glyphicon glyphicon-check"></span>&nbsp;
						Already Registered?
						<br>
						<b class="homeBig">Login</b>&nbsp;
						<span class="glyphicon glyphicon-log-in"></span>
					</div>
				</div>
			</div>
		</a>
	</div>
	<div class="row">
		<hr>
		<h3 style="text-align: center;">Register</h3>
		<a href="{% url 'accounts:signup' %}">
			<div class="col-sm-6 col-md-6 col-12">
				<div class="panel homePage" style="background-color: #FF5733;">
					<div class="panel-body">
						<span class="glyphicon glyphicon-user"></span>&nbsp;Student?
						<br>
						<b class="homeBig">Register as Student</b>&nbsp;
						<span class="glyphicon glyphicon-plus-sign"></span>		
					</div>
				</div>
			</div>
		</a>
		<a href="{% url 'accounts:signup-official'%}">
			<div class="col-sm-6 col-md-6 col-12">
				<div class="panel homePage" style="background-color: #900C3F;">
					<div class="panel-body">
						<span class="glyphicon glyphicon-user"></span>&nbsp;Official?
						<br>
						<b class="homeBig">Register as Official</b>&nbsp;
						<span class="glyphicon glyphicon-plus-sign"></span>
					</div>
				</div>
			</div>
		</a>
	</div>
	<div class="row">
		<hr>
		<h3 style="text-align: center;">Application Status</h3>
		<a href="{% url 'portal:application-status' %}">
			<div class="col-sm-4 col-md-4 col-12 col-sm-offset-4 col-md-offset-4">
				<div class="panel homePage" style="background-color: #FFC300;">
					<div class="panel-body">
						<span class="glyphicon glyphicon-check"></span>&nbsp;
						Already filled the form?
						<br>
						<b class="homeBig">Check Application status</b>&nbsp;
						<span class="glyphicon glyphicon-log-in"></span>
					</div>
				</div>
			</div>
		</a>
	</div>
</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/profile_base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
			<div class="col-sm-offset-3 col-md-offset-3 col-sm-6 col-md-6">
				<div class="panel">
					<div class="panel-body">
						{% include 'accounts/messages.html' %}
						<h3>Login</h3>
						<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
							{% csrf_token %}
							<div>
								{% include 'accounts/form_template.html' %}
								<div class="submit-row" style="text-align: left;">
									<button type="submit" class="btn btn-success">Login</button>
									<a href="{% url 'accounts:password-reset' %}" style="float: right;">Forgot your password?</a>
									<span style="float: right;">&nbsp;|&nbsp;</span>
									<a href="{% url 'home_page' %}" style="float: right;">Register</a>
								</div>
							</div>	
						</form>
					</div>
				</div>
			</div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/messages.html
{% for message in messages %}
	<div class="alert {{ message.tags }} alert dismissible" role="alert">
		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		{{ message }}
	</div>
{% endfor %}

accounts/templates/accounts/official_register.html
{% extends 'accounts/profile_base.html' %}

{% block title %}Official Register{% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-offset-3 col-md-offset-3 col-sm-6 col-md-6">
				<div class="panel">
					<div class="panel-body">
						{% include 'accounts/messages.html' %}
						<h3 class="text-center">Register</h3>
						<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
							{% csrf_token %}
							<div>
								{% include 'accounts/profile_form_template.html' %}
								<div class="submit-row onesubmit">
									<button type="submit" class="btn btn-success">Signup</button>
								</div>
							</div>
						</form>
					</div>
				</div>
		</div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'accounts/profile_base.html' %}

{% block title %}Password set{% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-offset-4 col-md-offset-4 col-sm-4 col-md-4">
			<div class="panel">
				<div class="panel-body">
					<p>Your password has been set. You can <a href="{% url 'accounts:login' %}">log in</a> now.</p>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'accounts/profile_base.html' %}

{% block title %}Enter Password{% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-offset-3 col-md-offset-3 col-sm-6 col-md-6">
			<div class="panel">
				<div class="panel-body">
					{% include 'accounts/messages.html' %}
					{% if validlink %}
						<p>Please enter your new password twice</p>
						<form class="form-horizontal" action="" method="post">
							{% csrf_token %}
							<div>
								{% include 'accounts/form_template.html' %}
								<div class="submit-row onesubmit">
									<button type="submit" class="btn btn-success">Set password</button>
								</div>
							</div>	
						</form>
					{% else %}
						<p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset</p>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'accounts/profile_base.html' %}

{% block title %}Email sent{% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-offset-4 col-md-offset-4 col-sm-4 col-md-4">
			<div class="panel">
				<div class="panel-body">
					<div class="container-fluid">
						<p>E-mail Sent</p>
					</div>
					<div class="container-fluid">
						<p>We've mailed you instructions for setting your new password.</p>
						<p>If yout don't receive an email, please make sure you've entered the email you registered with.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email : {{ email }}. Follow the link below to:
{{ protocol }}://{{ domain }}{% url 'accounts:password-reset-confirm' uidb64=uid token=token %}
Your username, in case you've forgotten: {{ user.get_username }}

accounts/templates/accounts/password_reset_form.html
{% extends 'accounts/profile_base.html' %}

{% block title %}Enter E-mail id{% endblock %}

{% block content %}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-offset-3 col-md-offset-3 col-sm-6 col-md-6">
				<div class="panel">
					<div class="panel-body">
						{% include 'accounts/messages.html' %}
						<h3 class="text-center">Enter E-mail to set new password</h3>
						<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
							{% csrf_token %}
							<div>
								{% include 'accounts/form_template.html' %}
								<div class="submit-row onesubmit">
									<button type="submit" class="btn btn-success">Send E-mail</button>
								</div>
							</div>	
						</form>
					</div>
				</div>
		</div>
	</div>
</div>
		
{% endblock %}

accounts/templates/accounts/profile_form_template.html
<fieldset class="module aligned">
	{% for field in user_form %}
		<div class="form-row">
			<div class="text-center">
				{{field.error}}
			</div>
			<div>
				<label class="required">
					{{ field.label_tag }} 
				</label>
				{{ field }}
			</div>
			{% if field.help_text %}
				<div class="help" style="color: gray;">{{ field.help_text|safe }}</div>
			{% endif %}
		</div>
	{% endfor %}
	{% for field in profile_form %}
		<div class="form-row">
			<div class="text-center">
				{{field.error}}
			</div>
			<div>
				<label class="required">
					{{ field.label_tag }} 
				</label>
				{{ field }}
			</div>
			{% if field.help_text %}
				<div class="help" style="color: gray;">{{ field.help_text }}</div>
			{% endif %}
		</div>
	{% endfor %}
</fieldset>