api/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from rest_framework import routers
from api.views import views_portal, views_accounts, views_authentication

router = routers.DefaultRouter()
router.register('slot',views_portal.SlotView, base_name="slotList")
router.register('application', views_portal.ApplicationView, base_name="applicationList")
router.register('fee', views_portal.FeeView, base_name="feeList")
router.register('applicant', views_accounts.ApplicantView, base_name="applicatnList")
router.register('user', views_accounts.UserView, base_name="userList")

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^login/$', views_authentication.LoginView.as_view(), name='api_login'),
    # URLs that require a user to be logged in with a valid session / token.
    url(r'^logout/$', views_authentication.LogoutView.as_view(), name='api_logout'),
]

portal/urls.py
from django.conf.urls import url
from . import views
from portal.views import views_applicant as applicant
from portal.views import views_official as official

app_name = 'portal'

urlpatterns = [
	#applicant urls
	url(r'^index/$', applicant.index, name="index"),
	url(r'^internship/form/$', applicant.internship_form, name="internship-form"),
	url(r'^internship/details/$', applicant.internship_details, name="internship-details"),
	url(r'^internship/edit/$', applicant.edit_internship, name="internship-edit"),
	url(r'^applications/$', applicant.application_home, name="applications"),
	url(r'^application/form/(?P<pk>\d+)/$', applicant.application_form, name="application-form"),
	url(r'^application/filled/(?P<pk>\d+)/$', applicant.application_filled, name="application-filled"),
	url(r'^application/status/$', applicant.application_status, name='application-status'),
	url(r'^pay/fee/(?P<pk>\d+)/$', applicant.pay_fees, name="pay-fee"),
	url(r'^pay/fee/online/(?P<pk>\d+)/$', applicant.pay_fee_online, name="pay-fee-online"),
	url(r'^pay/fee/challan/(?P<pk>\d+)/$', applicant.pay_fee_challan, name="pay-fee-challan"),
	url(r'^pay/fee/(?P<pk>\d+)/paid$', applicant.fees_paid, name="fees-paid"),
	url(r'^final/list/$', applicant.final_list, name="final-list"),
	url(r'^get/documents/(?P<pk>\d+)/$', applicant.get_documents, name="get-documents"),
	#official urls
	url(r'^application/all/$', official.all_applications, name="all-applications"),
	url(r'^application/(?P<pk>\d+)/$', official.application_details, name="application-details"),
	url(r'^application/verify/(?P<pk>\d+)/$', official.application_verify, name="application-verify"),
	url(r'^application/reject/(?P<pk>\d+)/$', official.application_reject, name="application-reject"),
	url(r'^slot/new/$', official.create_slot, name="create-slot"),
	url(r'^slot/(?P<pk>\d+)/edit/$', official.edit_slot, name="edit-slot"),
	url(r'^slot/all/$', official.all_slots, name="all-slots"),
	url(r'^slot/(?P<pk>\d+)/delete/$', official.DeleteSlot.as_view(), name='delete-slot'),
	url(r'^fess/payments/all/$', official.all_fees, name="all-fees"),
	url(r'^fee/(?P<pk>\d+)/details$', official.fee_details, name="fee-details"),
	url(r'^fee/verify/(?P<pk>\d+)/$', official.fee_verify, name="fee-verify"),
	url(r'^fee/reject/(?P<pk>\d+)/$', official.fee_reject, name="fee-reject"),
	#docs
	url(r'^acknowledgement/(?P<pk>\d+)/$', applicant.acknowledgement_slip, name="acknowledgement"),
	url(r'^acceptance/(?P<pk>\d+)/$', applicant.acceptance_letter, name="acceptance"),
	url(r'^temp-pass/(?P<pk>\d+)/$', applicant.temp_pass, name="temp-pass"),
	url(r'^attendance/(?P<pk>\d+)/$', applicant.attendance_letter, name="attendance"),
	url(r'^clearance/(?P<pk>\d+)/$', applicant.clearance_letter, name="clearance"),
	url(r'^bond/(?P<pk>\d+)/$', applicant.bond_format, name="bond"),
	url(r'^rules/$', applicant.rules, name="rules"),
]

portalsite/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from accounts.views import home_page
from portal.views import views_applicant


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name='home_page'),
    url(r'^about/$', views_applicant.about, name='about'),
    url(r'^contact/$', views_applicant.contact, name='contact'),
    url(r'^help/$', views_applicant.help_content, name='help'),
    url(r'^portal/', include('portal.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^feedback/',include('feedback.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

portal/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.utils import timezone
import datetime

# Create your models here.
class Slot(models.Model):
	start_date = models.DateField(default=timezone.now, null=True)
	end_date = models.DateField(default=timezone.now, null=True)
	duration = models.IntegerField(default=7,null=True)
	max_strength = models.IntegerField(default=10,null=True)
	present_strength = models.IntegerField(default=0,null=True)
	is_filled = models.BooleanField(default=False)

	def get_absolute_url(self):
		return reverse('portal:all-slots')

	def __str__(self):
		return str(self.start_date) + " - " + str(self.end_date) + " :: " + str(self.present_strength) + " filled"

class Application(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	application_no = models.CharField(max_length=8, default='00XX0000')
	applicant_name = models.CharField(max_length=250, default='')
	GENDER_CHOICES = (
		('M','Male'),
		('F','Female'),
	)
	gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='M')
	caste = models.CharField(max_length=100, default='')
	residence_address = models.TextField(default='')
	college_name = models.CharField(max_length=500, default='')
	college_address = models.TextField(default='')
	mobile_no = models.CharField(max_length=10,default='')
	date_of_birth = models.DateField(default=timezone.now)
	email = models.EmailField(null=True)
	applicant_photo = models.FileField(null=True, help_text="upload jpg, jpeg, png files only", validators=[FileExtensionValidator(['jpg','png','jpeg'])])
	noc = models.FileField(null=True,help_text="upload pdf,jpg,jpeg,png files only with size less than 2mb")
	caste_certificate = models.FileField(null=True,help_text="upload pdf,jpg,jpeg,png files only with size less than 2mb")
	internship_type = models.CharField(max_length=50, default="Training")
	duration = models.IntegerField(default=7)
	slot = models.ForeignKey(Slot, on_delete=models.CASCADE, null=True)
	course = models.CharField(max_length=250,default='')
	year_of_study = models.CharField(max_length=10, default='Third')
	department = models.CharField(max_length=250, default='')
	is_application_filled = models.BooleanField(default=False)
	verified = models.BooleanField(default=False)
	remarks = models.TextField(null=True)

	def get_absolute_url(self):
		return reverse('portal:application-filled')

	def __str__(self):
		return self.application_no

class Fee(models.Model):
	application = models.OneToOneField(Application, on_delete=models.CASCADE)
	fee_receipt = models.FileField(null=True,help_text="upload pdf,jpg,jpeg,png files only with size less than 2mb")
	FEE_CHOICES = (
		('O', 'Online'),
		('C', 'Challan'),
	)
	fee_type = models.CharField(max_length=1, choices=FEE_CHOICES, default='O')
	transaction_no = models.CharField(max_length=20,default='')
	fees = models.FloatField(default=200.0)
	paid_on = models.DateTimeField(default=timezone.now,help_text="enter only date in yyyy/mm/dd format")
	is_fees_paid = models.BooleanField(default=False)
	verified = models.BooleanField(default=False)
	remarks = models.TextField(null=True)

	def get_absolute_url(self):
		return reverse('portal:applications')

	def __str__(self):
		return str(self.transaction_no)

portal/forms.py
from django import forms
from .models import Application, Fee, Slot
from accounts.models import Applicant
import datetime

class InternshipForm(forms.ModelForm):
	slot = forms.ModelChoiceField(queryset=Slot.objects.all())
	class Meta:
		model = Applicant
		fields = ['internship_type', 'duration','slot','course','department','group_strength']
		widgets = {'internship_type':forms.Select(),'department':forms.Select(),'slot':forms.Select()}

class ApplicationForm(forms.ModelForm):
	class Meta:
		model = Application
		fields = ['applicant_name','gender','caste','mobile_no','email','date_of_birth','residence_address','college_name','college_address','year_of_study','applicant_photo','noc','caste_certificate',]
		widgets = {'gender':forms.RadioSelect(),'date_of_birth':forms.SelectDateWidget(years=range(1980,2018))}

class FeePayForm(forms.ModelForm):
	class Meta:
		model = Fee
		fields = ['fee_type']
		widgets = {'fee_type':forms.RadioSelect()}

class FeeForm(forms.ModelForm):
	class Meta:
		model = Fee
		fields = ['transaction_no','fees','paid_on','fee_receipt']

class ApplicationRemarksForm(forms.ModelForm):
	class Meta:
		model = Application
		fields = ['remarks',]

class FeeRemarksForm(forms.ModelForm):
	class Meta:
		model = Fee
		fields = ['remarks',]

class SlotForm(forms.ModelForm):
 	class Meta:
 		model = Slot
 		fields = ['start_date', 'end_date','duration', 'max_strength']
 		widgets = {'start_date':forms.SelectDateWidget(years=range(datetime.date.today().year,datetime.date.today().year + 1)), 'end_date':forms.SelectDateWidget(years=range(datetime.date.today().year,datetime.date.today().year + 2))}

portal/views/views_official.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q
import datetime
import re
from portal.models import Application, Fee, Slot
from accounts.models import Applicant, Official
from portal.forms import ApplicationRemarksForm, SlotForm, FeeRemarksForm

#official views

@login_required
def create_slot(request):
	try:
		if request.user.official:
			if request.method == 'POST':
				form = SlotForm(request.POST)
				if form.is_valid():
					form.save()
					return redirect('portal:all-slots')
			else:
				form = SlotForm()
			return render(request, 'official/create_slot.html', {'form':form})
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

@login_required
def edit_slot(request,pk):
	try:
		if request.user.official:
			slot = get_object_or_404(Slot, pk=pk)
			if request.method == 'POST':
				form = SlotForm(request.POST, instance=slot)
				if form.is_valid():
					form.save()
					return redirect('portal:all-slots')
			else:
				form = SlotForm(instance=slot)
			return render(request, 'official/create_slot.html', {'form':form})
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

@login_required
def all_slots(request):
	try:
		if request.user.official:
			slots = Slot.objects.all().order_by('start_date')
			return render(request, 'official/all_slots.html', {'slots':slots})
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

@method_decorator(login_required, name='dispatch')
class DeleteSlot(DeleteView):
    model = Slot
    template_name = 'official/slot_confirm_delete.html'
    success_url = reverse_lazy('portal:all-slots')

@login_required
def all_applications(request):
	try:
		if request.user.official:
			query = request.GET.get("q")
			if query:
				match_app_no = re.match(r'\d{2}[a-zA-Z]{2}\d{4}', query)
				if match_app_no:
					try:
						application = Application.objects.get(application_no=query)
						return render(request, 'official/all_applications.html', {'search_app':application})
					except Application.DoesNotExist:
						messages.error(request, "No application found with {}".format(query))
				else:
					messages.error(request, "Invalid application number")
			applications = Application.objects.all().order_by('pk')
			return render(request, 'official/all_applications.html', {'applications':applications})
	except Official.DoesNotExist:
		messages.error(request,"Not authorized")
		return redirect('portal:index')

@login_required
def application_details(request,pk):
	try:
		if request.user.official:
			application = get_object_or_404(Application, pk=pk)
			return render(request, 'official/application_details.html', {'application':application})
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

@login_required
def application_verify(request,pk):
	try:
		if request.user.official:
			application = get_object_or_404(Application, pk=pk)
			if application.is_application_filled == True:
				application.verified = True
				application.remarks = "Application accepted"
				application.save()
				applications = Application.objects.filter(user=application.user)
				fee = Fee.objects.create(application=application)
				fee.fees = 200.00
				fee.save()
				messages.success(request,"Application verified")
				return redirect('portal:application-details',pk=pk)
			else:
				messages.error(request,"Application not filled yet")
				return redirect('portal:index')
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

@login_required
def application_reject(request,pk):
	try:
		if request.user.official:
			application = get_object_or_404(Application , pk=pk)
			if request.method == 'POST':
				form = ApplicationRemarksForm(request.POST)
				if form.is_valid():
					application.remarks = form.cleaned_data['remarks']
					application.is_application_filled = False
					application.save()
					messages.info(request, "Application rejected")
					return redirect('portal:application-details',pk=pk)
			else:
				form = ApplicationRemarksForm()
			return render(request, 'official/remarks.html', {'form':form})
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

@login_required
def all_fees(request):
	try:
		if request.user.official:
			query = request.GET.get("q")
			if query:
				try:
					transaction = Fee.objects.get(transaction_no=query)
					return render(request, 'official/all_fees.html', {'transaction':transaction})
				except Fee.DoesNotExist:
					messages.error(request, "No transaction found with {}".format(query))
			fees = Fee.objects.filter(is_fees_paid=True).order_by('pk')
			return render(request, 'official/all_fees.html', {'fees':fees})
	except Official.DoesNotExist:
		messages.error(request,"Not authorized")
		return redirect('portal:index')

@login_required
def fee_details(request,pk):
	try:
		if request.user.official:
			fee = get_object_or_404(Fee, pk=pk)
			return render(request, 'official/fee_details.html', {'fee':fee})
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

@login_required
def fee_verify(request,pk):
	try:
		if request.user.official:
			fee = get_object_or_404(Fee, pk=pk)
			if fee.is_fees_paid == True:
				fee.verified = True
				fee.remarks = "Application accepted"
				fee.save()
				applications = Application.objects.filter(user=fee.application.user)
				applicant_of_app = fee.application.user.applicant
				fees_no = 0
				for app in applications:
					try:
						if app.fee:
							if app.fee.verified:
								fees_no += 1
					except:
						pass
				if fees_no == applications.count():
					applicant_of_app.reporting_date = str(applicant_of_app.slot.start_date) + " " + str(datetime.time(hour=10, minute=0))
					applicant_of_app.is_group_formed = True
				applicant_of_app.save()
				messages.success(request,"Fee payment details verified")
				return redirect('portal:fee-details',pk=pk)
			else:
				messages.error(request,"Fee not paid yet")
				return redirect('portal:index')
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

@login_required
def fee_reject(request,pk):
	try:
		if request.user.official:
			fee = get_object_or_404(Fee , pk=pk)
			if request.method == 'POST':
				form = FeeRemarksForm(request.POST)
				if form.is_valid():
					fee.remarks = form.cleaned_data['remarks']
					fee.is_fees_paid = False
					fee.save()
					messages.info(request, "Fee payment rejected")
					return redirect('portal:fee-details',pk=pk)
			else:
				form = FeeRemarksForm()
			return render(request, 'official/remarks.html', {'form':form})
	except Official.DoesNotExist:
		messages.error(request, "Not authorized")
		return redirect('portal:index')

portal/templates/official/all_slots.html
{% extends 'applicant/base.html' %}

{% block title %}All slots{% endblock %}

{% block content %}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-offset-2 col-md-offset-2 col-sm-8 col-md-8 col-12">
			<div class="panel panel-default">
				<div class="panel-body">
					{% include 'official/messages.html' %}
					<h3 class="text-center">All Slots</h3>
					<div class="text-center">
						<a href="{% url 'portal:create-slot' %}"><button type="button" class="btn btn-success">Create slot</button></a>
					</div>
					
					<div class="table-responsive" style="margin-top: 20px;">
						<table class="table">
							<thead>
								<tr>
									<th>Start date</th>
									<th>End date</th>
									<th>Duration</th>
									<th>Max people</th>
									<th>Present strength</th>
									<th>Filled?</th>
									<th>Edit</th>
									<th>Delete slot</th>
								</tr>
							</thead>
							<tbody>
								{% for slot in slots %}
									<tr>
										<td>{{ slot.start_date }}</td>
										<td>{{ slot.end_date }}</td>
										<td>{{ slot.duration }}</td>
										<td>{{ slot.max_strength }}</td>
										<td>{{ slot.present_strength }}</td>
										<td>{{ slot.is_filled }}</td>
										<td><a href="{% url 'portal:edit-slot' slot.id %}"><button type="button" class="btn btn-info btn-xs">Edit</button></a></td>
										<td>
											<form action="{% url 'portal:delete-slot' slot.id %}" method="get">
												{% csrf_token %}
												<input type="hidden" name="slot_id" value="{{ slotID }}">
												<button type="submit" class="btn btn-danger btn-xs" style="background-color: red;">Delete</button>
											</form>
										</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
					
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

portal/templates/official/application_details.html
{% extends 'applicant/base.html' %}

{% block title %}Application Details{% endblock %}

{% block content %}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-offset-3 col-md-offset-3 col-sm-6 col-md-6 col-12">
			<div class="panel panel-default">
				<div class="panel-body">
					{% include 'official/messages.html' %}
					<div style="border: 1px solid black;height: 142px;width: 110px; margin: 0 auto;">
						<img src="{{ application.applicant_photo.url }}" alt="{{ application.applicant_name }}" width="110px" />
					</div>
					<table class="table table-bordered">
						<thead>
							<tr>
								<th colspan="4" style="text-align: center;">
									<h3>{{ application.application_no }}</h3>
								</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th>Name</th>
								<td>
									{{ application.applicant_name }}
								</td>
								<th>Date of birth</th>
								<td>{{ application.date_of_birth }}</td>
							</tr>
							<tr>
								<th>Mobile no</th>
								<td>{{ application.mobile_no }}</td>
								<th>E-mail</th>
								<td>{{ application.email }}</td>		
							</tr>
							<tr>
								<th>Gender</th>
								<td>{{ application.get_gender_display }}</td>
								<th>Caste</th>
								<td>{{ application.caste }}</td>
							</tr>
							<tr>
								<th>Course</th>
								<td>{{ application.course }}</td>
								<th>Department</th>
								<td>{{ application.user.applicant.get_department_display }}</td>
							</tr>
							<tr>
								<th>College name</th>
								<td colspan="3">{{ application.college_name }}</td>
							</tr>
							<tr>
								<th>College Address</th>
								<td colspan="3">{{ application.college_address }}</td>
							</tr>
							<tr>
								<th>Residential Adddress</th>
								<td colspan="3">{{ application.residence_address }}</td>
							</tr>
							<tr>
								<th>Internship type</th>
								<td>{{ application.user.applicant.get_internship_type_display }}</td>
								<th>Slot</th>
								<td>{{ application.slot.start_date }} - {{ application.slot.end_date }} </td>
							</tr>
							<tr>
								<th>Group leader username</th>
								<td colspan="3">{{ application.user }}</td>
							</tr>
							<tr>
								<th colspan="4" class="text-center">Documents uploaded</th>
							</tr>
							<tr>
								<th>NOC</th>
								<td><a href="{{ application.noc.url }}">View</a></td>
								<th>Caste certificate</th>
								<td><a href="{{ application.caste_certificate.url }}">View</a></td>
							</tr>
						</tbody>
					</table>
					<h2 class="text-center">Actions on application</h2>
					<div class="submit-row onesubmit">
						{% if not application.verified %}
							<a href="{% url 'portal:application-verify' application.id %}"><button type="button" class="btn btn-success">Verified</button></a>
							<a href="{% url 'portal:application-reject' application.id %}"><button type="button" class="btn btn-danger">Reject</button></a>
						{% else %}
							Application Verified
						{% endif %}
					</div>
					<h2 class="text-center">Action on fee payment</h2>
					<div class="submit-row onesubmit">
						{% if application.fee.is_fees_paid %}
							{% if application.fee.verified %}
								Fee payment verified
							{% else %}
								<a href="{% url 'portal:fee-details' application.fee.id %}"><button type="button" class="btn btn-info">View Fee Details</button></a>
							{% endif %}
						{% else %}
							Fee not paid
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

portal/templates/official/create_slot.html
{% extends 'applicant/base.html' %}

{% block title %}Remarks{% endblock %}

{% block content %}

<div class="container-fluid">
		<div class="row">
			<div class="col-sm-offset-3 col-md-offset-3 col-sm-6 col-md-6">
				<div class="panel">
					<div class="panel-body">
						<h3 class="text-center">Slot</h3>
						{% include 'official/messages.html' %}
						<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
							{% csrf_token %}
							<div>
								{% include 'official/form_template.html' %}
								<div class="submit-row onesubmit">
									<button type="submit" class="btn btn-danger">Save</button>
								</div>
							</div>	
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

portal/templates/official/fee_details.html
{% extends 'applicant/base.html' %}

{% block title %}Fee Payment Details{% endblock %}

{% block content %}

<div class="container-fluid">
		<div class="row">
			<div class="col-sm-offset-3 col-md-offset-3 col-sm-6 col-md-6">
				<div class="panel">
					<div class="panel-body">
						{% include 'official/messages.html' %}
						<h3 class="text-center">Fees details</h3>
						<table class="table">
							<tbody>
								<tr>
									<th>Transaction no : </th>
									<td>{{ fee.transaction_no }}</td>
								</tr>
								<tr>
									<th>Application no : </th>
									<td>{{ fee.application.application_no }}</td>
								</tr>
								<tr>
									<th>Applicant name : </th>
									<td>{{ fee.application.applicant_name }}</td>
								</tr>
								<tr>
									<th>Fee paid : </th>
									<td>{{ fee.fees }}</td>
								</tr>
								<tr>
									<th>Paid on : </th>
									<td>{{ fee.paid_on }}</td>
								</tr>
								<tr>
									<th>Paid through : </th>
									<td>{{ fee.get_fee_type_display }}</td>
								</tr>
								<tr>
									<th>Receipt : </th>
									<td><a href="{{ fee.fee_receipt.url }}">View</a></td>
								</tr>
								<tr>
									<th>Application : </th>
									<td><a href="{% url 'portal:application-details' fee.application.id %}">View</a></td>
								</tr>
							</tbody>
						</table>
						<div class="submit-row">
							{% if fee.is_fees_paid %}
								{% if fee.verified %}
									Fee payment verified
								{% else %}
									<a href="{% url 'portal:fee-verify' fee.id %}"><button type="button" class="btn btn-success">Payment Verified</button></a>
									<a href="{% url 'portal:fee-reject' fee.id %}"><button type="button" class="btn btn-danger">Reject Payment</button></a>
								{% endif %}
							{% endif %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

portal/templates/official/form_template.html
<fieldset class="module aligned">
	{% for field in form %}
		<div class="form-row">
			<div>
				<label class="required">
					{{ field.label_tag }} 
				</label>
				{{ field }}
			</div>
			{% if field.help_text %}
				<div class="help" style="color: gray;">{{ field.help_text }}</div>
			{% endif %}
		</div>
	{% endfor %}
</fieldset>

portal/templates/official/messages.html
{% for message in messages %}
	<div class="alert {{ message.tags }} alert dismissible" role="alert">
		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		{{ message }}
	</div>
{% endfor %}

portal/templates/official/official_index.html
{% extends 'applicant/base.html' %}

{% block title %}Student Portal{% endblock %}

{% block content %}

<div class="container-fluid">
	<div class="row">
		{% include 'official/messages.html' %}
		<div class="submit-row onesubmit">
			<a href="{% url 'portal:all-slots' %}"><button type="button" class="btn btn-info">All slots</button></a>
			<a href="{% url 'portal:create-slot' %}"><button type="button" class="btn btn-info">Create slot</button></a>
		</div>
		<div class="col-sm-6 col-md-6 col-12">
			<div class="panel panel-default">
				<div class="panel-body">	
					<div class="submit-row onesubmit">
						<a href="{% url 'portal:all-applications' %}"><button type="button" class="btn btn-info">All applications</button></a>
					</div>
						<table class="table">
							<thead>
								<th colspan="2">Applications to be verified</th>
							</thead>
							<tbody>
								{% for application in applications %}
									<tr>
										{% if not application.verified and application.is_application_filled %}
											<td>{{ application.application_no }}</td>
											<td>{{ application.applicant_name }}</td>
											<td><a href="{% url 'portal:application-details' application.id %}"><button type="button" class="btn btn-success btn-sm">View</button></td>
										{% endif %}
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
		</div>
		<div class="col-sm-6 col-md-6 col-12">
			<div class="panel panel-default">
				<div class="panel-body">	
					<div class="submit-row onesubmit">
						<a href="{% url 'portal:all-fees' %}"><button type="button" class="btn btn-info">All fee payment details</button></a>
					</div>
						<table class="table">
							<thead>
								<th colspan="2">Fee payments to be verified</th>
							</thead>
							<tbody>
								{% for fee in fees %}
									<tr>
										{% if not fee.verified and fee.is_fees_paid %}
											<td>{{ fee.application.application_no }}</td>
											<td>{{ fee.application.applicant_name }}</td>
											<td>{{ fee.transaction_no }}</td>
											<td><a href="{% url 'portal:fee-details' fee.id %}"><button type="button" class="btn btn-success btn-sm">View</button></td>
										{% endif %}
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
		</div>
	</div>
</div>

{% endblock %}

portal/templates/official/slot_confirm_delete.html
{% extends 'applicant/base.html' %}

{% block content %}
<div class="container-fluid">
	<div class="panel panel-default text-center">
		<div class="panel-body">
			<p>Are you sure you want to delete "{{ slot }}"?</p>
			<form method="post">
				{% csrf_token %}
				<input type="button" value="Cancel" class="btn btn-success" onclick="window.history.go(-1);" />
			    <input type="submit" value="Confirm" class="btn btn-danger" />
			</form>
		</div>
	</div>
</div>
{% endblock %}